// -----------------------------------------------------------------------------
// Author: Cedric Hölzl
//
// Description:
//   SystemC wrapper for the Verilated SV top_crossbar (Verilator --sc output).
//   Mirrors the port convention of the native rtl/systemc/top_crossbar.hpp so
//   that tb_top_crossbar.cpp can swap between the two DUTs by changing a single
//   #include and the class name.
//
//   The Verilated module (Vtop_crossbar) exposes the OBI request/response struct
//   arrays as flat wide bit vectors:
//     ragu_req_i  : sc_in <sc_bv<NUM_MGR  * OBI_REQ_W>>   (packed obi_req_t array)
//     ragu_resp_o : sc_out<sc_bv<NUM_MGR  * OBI_RESP_W>>  (packed obi_resp_t array)
//     wagu_req_i  : sc_in <sc_bv<NUM_WMGR * OBI_REQ_W>>
//     wagu_resp_o : sc_out<sc_bv<NUM_WMGR * OBI_RESP_W>>
//
//   OBI struct field layout (SystemVerilog packed, LSB = field declared last):
//     obi_req_t (OBI_REQ_W bits per manager):
//       [OBI_DW-1        :  0       ] wdata
//       [OBI_DW+31       :  OBI_DW  ] addr
//       [OBI_DW+32+BEW-1 :  OBI_DW+32] be
//       [OBI_DW+32+BEW   ]            we
//       [OBI_DW+32+BEW+1 ]            req
//     obi_resp_t (OBI_RESP_W bits per manager):
//       [OBI_DW-1 :  0      ] rdata
//       [OBI_DW   ]           rvalid
//       [OBI_DW+1 ]           gnt
//
//   OBI_DATA_WIDTH must be passed consistently via PARAMS= so that Verilator
//   receives -G and C++ receives -D with the same value.  With the 32-bit AGU
//   testbench use PARAMS=OBI_DATA_WIDTH=32 (OBI_REQ_W=70, OBI_RESP_W=34).
//   Default is 128 to match obi_pkg.sv; uint64_t ports truncate data above 64 b.
//
//   This wrapper packs/unpacks those into individual per-manager sc_in/sc_out
//   arrays (m_req_i / m_w_req_i, …) that match the native top_crossbar.hpp
//   port names. Four SC_METHODs keep the packed signals in sync.
//
//   Template parameters:
//     NUM_RAGU   - number of read  AGUs (default 7)
//     NUM_WAGU  - number of write AGUs (default 6)
//     NUM_REQ   - request ports per AGU (default 4)
//     NUM_BANK  - number of memory banks (default 32)
//     NUM_ROW   - rows per bank (default 1024)
// -----------------------------------------------------------------------------

#ifndef TOP_CROSSBAR_SV_HPP
#define TOP_CROSSBAR_SV_HPP

#include <systemc.h>

#include <cstdint>

#include "Vtop_crossbar.h" // generated by Verilator --sc

template <int NUM_RAGU = 2, int NUM_WAGU = 2, int NUM_REQ = 4, int NUM_BANK = 8, int NUM_ROW = 1024,
          int BYTES_PER_WORD = 4, int WORDS_PER_ROW = 4>
SC_MODULE(top_crossbar_sv) {
    static constexpr int NUM_MGR  = NUM_RAGU * NUM_REQ;
    static constexpr int NUM_WMGR = NUM_WAGU * NUM_REQ;
    static_assert(NUM_MGR <= 32, "NUM_MGR  > 32: req/we/gnt/rvalid bitmasks overflow uint32_t");
    static_assert(NUM_WMGR <= 32, "NUM_WMGR > 32: req/we/gnt/rvalid bitmasks overflow uint32_t");

    // OBI field widths — mirror obi_pkg.sv's OBI_DATA_WIDTH (set via PARAMS=OBI_DATA_WIDTH=<n>).
    // run.sh propagates each PARAMS entry as both -G<key>=<val> (to Verilator) and
    // -D<key>=<val> (to C++), so both the Verilated port widths and these constants track
    // together.  The port arrays use uint64_t, so OBI_DW > 64 silently truncates data.
    // Default 128 matches obi_pkg.sv; use PARAMS=OBI_DATA_WIDTH=32 with the 32-bit AGU tb.
#ifndef OBI_DATA_WIDTH
#define OBI_DATA_WIDTH 128
#endif
    static constexpr int OBI_DW     = OBI_DATA_WIDTH;
    static constexpr int OBI_BEW    = OBI_DW / 8;
    static constexpr int OBI_REQ_W  = OBI_DW + 32 + OBI_BEW + 2;
    static constexpr int OBI_RESP_W = OBI_DW + 2;

    // Clock and reset
    sc_in<bool> clk_i;
    sc_in<bool> rst_ni;

    // Manager-side ports: one OBI channel per manager port
    sc_in<bool>      m_req_i[NUM_MGR];
    sc_in<uint64_t>  m_addr_i[NUM_MGR]; // upper 32 bits ignored; OBI is 32-bit
    sc_in<bool>      m_we_i[NUM_MGR];
    sc_in<uint32_t>  m_be_i[NUM_MGR];
    sc_in<uint64_t>  m_wdata_i[NUM_MGR]; // upper 32 bits ignored
    sc_out<bool>     m_gnt_o[NUM_MGR];
    sc_out<bool>     m_rvalid_o[NUM_MGR];
    sc_out<uint64_t> m_rdata_o[NUM_MGR]; // zero-extended from 32-bit OBI rdata

    sc_in<bool>      m_w_req_i[NUM_WMGR];
    sc_in<uint64_t>  m_w_addr_i[NUM_WMGR]; // upper 32 bits ignored; OBI is 32-bit
    sc_in<bool>      m_w_we_i[NUM_WMGR];
    sc_in<uint32_t>  m_w_be_i[NUM_WMGR];
    sc_in<uint64_t>  m_w_wdata_i[NUM_WMGR]; // upper 32 bits ignored
    sc_out<bool>     m_w_gnt_o[NUM_WMGR];
    sc_out<bool>     m_w_rvalid_o[NUM_WMGR];
    sc_out<uint64_t> m_w_rdata_o[NUM_WMGR]; // zero-extended from 32-bit OBI rdata

    // -----------------------------------------------------------------------
    // Verilated module instance
    // -----------------------------------------------------------------------
    Vtop_crossbar vdut;

    // -----------------------------------------------------------------------
    // Packed intermediate signals connecting to Verilated OBI struct ports.
    // Each obi_req_t[N] array flattens to N * OBI_REQ_W bits (LSB = slot 0).
    // -----------------------------------------------------------------------
    sc_signal<sc_bv<NUM_MGR * OBI_REQ_W>>   s_ragu_req;
    sc_signal<sc_bv<NUM_MGR * OBI_RESP_W>>  s_ragu_resp;
    sc_signal<sc_bv<NUM_WMGR * OBI_REQ_W>>  s_wagu_req;
    sc_signal<sc_bv<NUM_WMGR * OBI_RESP_W>> s_wagu_resp;

    // -----------------------------------------------------------------------
    // Pack individual per-manager SC signals → flat OBI struct bit vector.
    // obi_req_t layout (LSB-first): wdata | addr | be | we | req
    // -----------------------------------------------------------------------
    template <int N, int REQ_W>
    static void do_pack(sc_in<bool>(&req_i)[N], sc_in<uint64_t>(&addr_i)[N], sc_in<bool>(&we_i)[N],
                        sc_in<uint32_t>(&be_i)[N], sc_in<uint64_t>(&wdata_i)[N],
                        sc_signal<sc_bv<N * REQ_W>> & s_packed) {
        sc_bv<N * REQ_W> packed;
        for (int i = 0; i < N; ++i) {
            const int base = i * REQ_W;
            // wdata [OBI_DW-1:0]
            packed.range(base + OBI_DW - 1, base) = static_cast<uint64_t>(wdata_i[i].read());
            // addr [OBI_DW+31:OBI_DW]
            packed.range(base + OBI_DW + 32 - 1, base + OBI_DW) =
                static_cast<uint64_t>(addr_i[i].read());
            // be [OBI_DW+32+OBI_BEW-1:OBI_DW+32]
            packed.range(base + OBI_DW + 32 + OBI_BEW - 1, base + OBI_DW + 32) = be_i[i].read();
            // we [OBI_DW+32+OBI_BEW]
            packed[base + OBI_DW + 32 + OBI_BEW] = we_i[i].read() ? 1 : 0;
            // req [OBI_DW+32+OBI_BEW+1]
            packed[base + OBI_DW + 32 + OBI_BEW + 1] = req_i[i].read() ? 1 : 0;
        }
        s_packed.write(packed);
    }

    // -----------------------------------------------------------------------
    // Unpack flat OBI struct bit vector → individual per-manager SC signals.
    // obi_resp_t layout (LSB-first): rdata | rvalid | gnt
    // -----------------------------------------------------------------------
    template <int N, int RESP_W>
    static void do_unpack(const sc_signal<sc_bv<N * RESP_W>> &s_packed, sc_out<bool>(&gnt_o)[N],
                          sc_out<bool>(&rvalid_o)[N], sc_out<uint64_t>(&rdata_o)[N]) {
        const sc_bv<N * RESP_W> packed = s_packed.read();
        for (int i = 0; i < N; ++i) {
            const int base = i * RESP_W;
            // rdata [OBI_DW-1:0], zero-extended to 64 bits
            rdata_o[i].write(packed.range(base + OBI_DW - 1, base).to_uint64());
            // rvalid [OBI_DW]
            rvalid_o[i].write(packed[base + OBI_DW].to_bool());
            // gnt [OBI_DW+1]
            gnt_o[i].write(packed[base + OBI_DW + 1].to_bool());
        }
    }

    void pack_inputs() {
        do_pack<NUM_MGR, OBI_REQ_W>(m_req_i, m_addr_i, m_we_i, m_be_i, m_wdata_i, s_ragu_req);
    }
    void pack_w_inputs() {
        do_pack<NUM_WMGR, OBI_REQ_W>(m_w_req_i, m_w_addr_i, m_w_we_i, m_w_be_i, m_w_wdata_i,
                                     s_wagu_req);
    }
    void unpack_outputs() {
        do_unpack<NUM_MGR, OBI_RESP_W>(s_ragu_resp, m_gnt_o, m_rvalid_o, m_rdata_o);
    }
    void unpack_w_outputs() {
        do_unpack<NUM_WMGR, OBI_RESP_W>(s_wagu_resp, m_w_gnt_o, m_w_rvalid_o, m_w_rdata_o);
    }

    SC_CTOR(top_crossbar_sv) : vdut("vdut") {
        vdut.clk_i(clk_i);
        vdut.rst_ni(rst_ni);

        // Connect packed OBI struct ports to Verilated module
        vdut.ragu_req_i(s_ragu_req);
        vdut.ragu_resp_o(s_ragu_resp);
        vdut.wagu_req_i(s_wagu_req);
        vdut.wagu_resp_o(s_wagu_resp);

        // Combinatorial pack/unpack for read-AGU path
        SC_METHOD(pack_inputs);
        for (int i = 0; i < NUM_MGR; ++i)
            sensitive << m_req_i[i] << m_addr_i[i] << m_we_i[i] << m_be_i[i] << m_wdata_i[i];

        SC_METHOD(unpack_outputs);
        sensitive << s_ragu_resp;

        // Combinatorial pack/unpack for write-AGU path
        SC_METHOD(pack_w_inputs);
        for (int i = 0; i < NUM_WMGR; ++i)
            sensitive << m_w_req_i[i] << m_w_addr_i[i] << m_w_we_i[i] << m_w_be_i[i]
                      << m_w_wdata_i[i];

        SC_METHOD(unpack_w_outputs);
        sensitive << s_wagu_resp;
    }
};

#endif // TOP_CROSSBAR_SV_HPP
